# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/js01lte/setup-makefiles.shon

PRODUCT_COPY_FILES += \
	vendor/samsung/js01lte/proprietary/oneseg/bin/broadcastProcessObserver:/system/bin/broadcastProcessObserver \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bml.db:/system/etc/one-seg/bml.db \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_0.wav:/system/etc/one-seg/bmlrom_0.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_1.wav:/system/etc/one-seg/bmlrom_1.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_10.wav:/system/etc/one-seg/bmlrom_10.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_11.wav:/system/etc/one-seg/bmlrom_11.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_12.wav:/system/etc/one-seg/bmlrom_12.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_13.wav:/system/etc/one-seg/bmlrom_13.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_14.wav:/system/etc/one-seg/bmlrom_14.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_15.wav:/system/etc/one-seg/bmlrom_15.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_2.wav:/system/etc/one-seg/bmlrom_2.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_3.wav:/system/etc/one-seg/bmlrom_3.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_4.wav:/system/etc/one-seg/bmlrom_4.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_5.wav:/system/etc/one-seg/bmlrom_5.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_6.wav:/system/etc/one-seg/bmlrom_6.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_7.wav:/system/etc/one-seg/bmlrom_7.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_8.wav:/system/etc/one-seg/bmlrom_8.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/bmlrom_9.wav:/system/etc/one-seg/bmlrom_9.wav \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/debug.ini:/system/etc/one-seg/debug.ini \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/njccp932.ctb:/system/etc/one-seg/njccp932.ctb \
	vendor/samsung/js01lte/proprietary/oneseg/etc/one-seg/tvfiles_database.db:/system/etc/one-seg/tvfiles_database.db \
	vendor/samsung/js01lte/proprietary/oneseg/etc/permissions/mmb.xml:/system/etc/permissions/mmb.xml \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libBroadcastProcObs.so:/system/lib/libBroadcastProcObs.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libISDBT_tuner.so:/system/lib/libISDBT_tuner.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libOneSegfactorytest_jni_fb.so:/system/lib/libOneSegfactorytest_jni_fb.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libPGL.so:/system/lib/libPGL.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libbroadcastForOneSeg_jni.so:/system/lib/libbroadcastForOneSeg_jni.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libSDtvAout.so:/system/lib/libSDtvAout.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libSDtvService.so:/system/lib/libSDtvService.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libSDtvStack.so:/system/lib/libSDtvStack.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libSDtvVout.so:/system/lib/libSDtvVout.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libbroadcastForOneSeg_jni.so:/system/lib/libbroadcastForOneSeg_jni.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libmorpho_frame_interp2.so:/system/lib/libmorpho_frame_interp2.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libnextbitd.so:/system/lib/libnextbitd.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libnextbitservice_jni.so:/system/lib/libnextbitservice_jni.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libonesegbmlpeer.so:/system/lib/libonesegbmlpeer.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libonesegdmxdriver.so:/system/lib/libonesegdmxdriver.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libonesegdsmcc.so:/system/lib/libonesegdsmcc.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libonesegsp.so:/system/lib/libonesegsp.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libonesegutils.so:/system/lib/libonesegutils.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libsdsmcc.so:/system/lib/libsdsmcc.so \
	vendor/samsung/js01lte/proprietary/oneseg/lib/libsdtvh264decoder.so:/system/lib/libsdtvh264decoder.so

PRODUCT_PACKAGES += \
    ISDBT_FactoryTest \
#    MobileTV_JPN_PHONE_K
